### ISSUE TITLE
the wrapper script run-td-extract does not support accept --rows-per-chunk yet

### ISSUE THREAD

**Issue by agarwadekarm** [google/dwh-assessment-extraction-tool#124]
the wrapper script run-td-extract does not support accept --rows-per-chunk yet

**Comment by cyulysses-corp** [comment]
It works when I test it. Could you paste the error message for you? Did you put the "--" after the dbc specs in the example script (referring to `./run-td-extract.sh -j <terajdbc driver> --db-address <database address> --output <output path> --db-user <db user> -- --<optional parameter> <parameter value>` on the README page)?

**Comment by cyulysses-corp** [comment]
Closing this issue for now due to no response. Feel free to reopen if the suggested fix above doesn't work for you :-)
